CREATE DATABASE IF NOT EXISTS campus_digital_hub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE campus_digital_hub;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('customer','editor','super_admin') NOT NULL DEFAULT 'customer', status ENUM('active','blocked') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, slug VARCHAR(120) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL UNIQUE, description TEXT NOT NULL, price DECIMAL(10,2) NOT NULL DEFAULT 0, file_path VARCHAR(255) NOT NULL, cover_color VARCHAR(30) NOT NULL DEFAULT 'blue', is_active TINYINT(1) NOT NULL DEFAULT 1, sales_count INT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, total DECIMAL(10,2) NOT NULL, discount DECIMAL(10,2) NOT NULL DEFAULT 0, status ENUM('pending','paid','refunded','cancelled') NOT NULL DEFAULT 'pending', payment_gateway VARCHAR(30) NULL, transaction_id VARCHAR(190) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, price DECIMAL(10,2) NOT NULL, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE coupons (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, type ENUM('flat','percent') NOT NULL, value DECIMAL(10,2) NOT NULL, expires_at DATE NULL, usage_limit INT UNSIGNED NULL, used_count INT UNSIGNED NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE tickets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, subject VARCHAR(180) NOT NULL, message TEXT NOT NULL, status ENUM('open','pending','closed') NOT NULL DEFAULT 'open', admin_reply TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE faqs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question VARCHAR(255) NOT NULL, answer TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE settings (setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NOT NULL);
CREATE TABLE password_resets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;

INSERT INTO categories(name,slug) VALUES ('Study systems','study-systems'),('Career kits','career-kits'),('Creative tools','creative-tools');
INSERT INTO products(category_id,title,slug,description,price,file_path,cover_color,sales_count) VALUES
(1,'The Focus OS','focus-os','A calm, printable operating system for planning deep work, deadlines, and recovery.',18.00,'storage/focus-os.pdf','blue',142),
(2,'Portfolio Launch Kit','portfolio-launch','A practical portfolio framework with prompts, checklists, and polished case-study templates.',24.00,'storage/portfolio-launch.zip','orange',98),
(3,'Creator Content Planner','creator-planner','A flexible planning workspace for turning half-formed ideas into a consistent creative practice.',12.00,'storage/creator-planner.pdf','yellow',76),
(1,'Exam Week Reset','exam-reset','A focused seven-day reset for prioritizing revision without burning out.',9.00,'storage/exam-reset.pdf','dark',61);
INSERT INTO faqs(question,answer,sort_order) VALUES ('How do downloads work?','After a successful order, your files appear in My library. You can download them again whenever you need them.',1),('Can I get a refund?','Contact support within 14 days and include your order number. We review each request promptly.',2),('Are the files editable?','Each product page explains the included formats. Most templates include PDF and editable source files.',3);
INSERT INTO settings(setting_key,setting_value) VALUES ('site_name','Campus Digital Hub'),('currency','BDT'),('tax_percent','0'),('payment_gateway','sslcommerz'),('footer_text','Useful digital tools for the work ahead.') ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);
